<html>
<body>
<h2>Warehouse</h2>
<style> td, th {
    border: 1px solid black;
} </style>
<!-- ustawienie czarnego obramowania tabeli w CSS -->
<table>
    <thead>
    <tr>
        <th>item</th>
        <td>ID</td>
        <td>type</td>
        <td>qty</td>
        <th>status</th>
        <th>rent</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th>hammer</th>
        <td>#</td>
        <td>0001</td>
        <td>
            <button>borrow</button>
        </td>
    </tr>
    <tr>
        <th>screwdriver</th>
        <td>#</td>
        <td>0002</td>
        <td>
            <button>borrow</button>
        </td>
    </tr>
    <tr>
        <th>saw</th>
        <td>#</td>
        <td>0003</td>
        <td>
            <button>borrow</button>
        </td>
    </tr>
    <tr>
        <th>pliers</th>
        <td>#</td>
        <td>0004</td>
        <td>
            <button>borrow</button>
        </td>
    </tr>
    <tr>
        <th>power drill</th>
        <td>#</td>
        <td>0005</td>
        <td>
            <button>borrow</button>
        </td>
    </tr>
    </tbody>
</table>
</body>
</html>
